# Generated by Django 3.0.3 on 2020-03-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200315_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eprescription',
            name='Medicine',
        ),
        migrations.AddField(
            model_name='eprescription',
            name='Medicine',
            field=models.ManyToManyField(to='services.Medicine'),
        ),
    ]
